"""Updated ReferralCode model

Revision ID: 67129079dbc4
Revises: 81b2fb2c1670
Create Date: 2024-10-23 18:44:10.365789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67129079dbc4'
down_revision: Union[str, None] = '81b2fb2c1670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
