"""Updated ReferralCode model with Mapped

Revision ID: 81b2fb2c1670
Revises: 914c80ff9816
Create Date: 2024-10-23 09:52:28.891472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b2fb2c1670'
down_revision: Union[str, None] = '914c80ff9816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referral_codes', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('referral_codes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referral_codes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('referral_codes', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
